### PR TITLE
Use dvm tmp for docker downloads

### LINKED ISSUE #188: Need to manually copy the docker binary Fedora 29
If you are reporting a bug, please use the template below:

### Need to manually copy the docker binary Fedora 29

Presume due to disk partitioning, use of 'rename' command fails.

```
$ dvm --debug install 18.03.1-ce
The dvm home directory is: /home/richard/.dvm
dvm install 18.03.1-ce
Installing 18.03.1-ce...
2018/12/30 17:09:37 Checking if 18.03.1-ce can be found at https://download.docker.com/linux/static/stable/x86_64/docker-18.03.1-ce.tgz
2018/12/30 17:09:38 Downloading https://download.docker.com/linux/static/stable/x86_64/docker-18.03.1-ce.tgz
2018/12/30 17:10:29 Could not find a stable release for 18.03.1-ce, checking for a test release
2018/12/30 17:10:29 Checking if 18.03.1-ce can be found at https://download.docker.com/linux/static/test/x86_64/docker-18.03.1-ce.tgz
2018/12/30 17:10:30 Downloading https://download.docker.com/linux/static/test/x86_64/docker-18.03.1-ce.tgz

Attempted to fallback to downloading from the prerelease location after downloading from the stable location failed: Unable to copy /tmp/dvm719964574/docker-18.03.1-ce/docker/docker to /home/richard/.dvm/bin/docker/18.03.1-ce/docker: rename /tmp/dvm719964574/docker-18.03.1-ce/docker/docker /home/richard/.dvm/bin/docker/18.03.1-ce/docker: invalid cross-device link: Unable to copy /tmp/dvm300176997/docker-18.03.1-ce/docker/docker to /home/richard/.dvm/bin/docker/18.03.1-ce/docker: rename /tmp/dvm300176997/docker-18.03.1-ce/docker/docker /home/richard/.dvm/bin/docker/18.03.1-ce/docker: invalid cross-device link
[richard@green hellonode]$ dvm ls
	system (1.13.1)
	18.03.1-ce
->	18.06.1-ce
[richard@green hellonode]$ dvm use 18.03.1-ce
Now using Docker 18.03.1-ce
[richard@green hellonode]$ dvm current
system (1.13.1)
[richard@green hellonode]$ mv /tmp/dvm719964574/docker-18.03.1-ce/docker/* /home/richard/.dvm/bin/docker/18.03.1-ce/
[richard@green hellonode]$ dvm use 18.03.1-ce
Now using Docker 18.03.1-ce
[richard@green hellonode]$ dvm current
18.03.1-ce
[richard@green hellonode]$ 
```

### What should it have done?

Command should have copied the docker binaries.

### Helpful Context

Default disk partitioning:

```tmpfs on /tmp type tmpfs (rw,nosuid,nodev,seclabel)
/dev/mapper/fedora-home on /home type ext4 (rw,noatime,seclabel)
```

What version of dvm are you using?

```
$ dvm --version
Docker Version Manager version 1.0.1 (b5c28c8)
```

What is your Operating System?

Fedora 29

What is your shell (bash/powershell/cmd/fish)?
```
[richard@green hellonode]$ bash --version
GNU bash, version 4.4.23(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
[richard@green hellonode]$ which bash
/usr/bin/bash
```

How did you install dvm (command-line,chocolatey,homebrew)?

command-line

Do you like kittens? :smile_cat:

haha sure.

### PR DESCRIPTION
**Pull request by carolynvs**
Download docker binary to `~/.dvm/.tmp` instead of `/tmp/dvm-*` so that when we copy it into the dvm home directory afterwards we can always use a rename safely. This avoids this dreaded cross partition move error `invalid cross-device link`.

Fixes #188

### CODE REVIEW

**Comment by rgbkrk** [comment]
Since more options are coming in here, perhaps there should be a front facing `DvmOptions` struct that both `dvmDir` and `mirror` can be part of.

**Comment by carolynvs** [comment]
Yeah good call. The args list is getting unweildly.

Also Docker broke how binaries are staged ... again... Just found that out when I reran the regression tests. They removed the files from test.docker.com and put up a download script there instead.

Gonna see how small of a fix that I can do to keep things working for most people without doing massive surgery. So just the struct and a bit of cleanup, since we don't need to be running builds on go 1.7 anymore. 😀

**Comment by carolynvs** [comment]
@rgbkrk Ok, once you've reviewed and merged #191, this is the next one to look at.

I've redone it so that instead of having a half dozen global vars, we pass around a DvmOptions struct.

File: dvm-helper/internal/config/config.go [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+	Shell              string
+	Debug              bool
+	Silent             bool
+	IncludePrereleases bool
+	Logger             *log.Logger
+}
+
+func NewDvmOptions() DvmOptions {
+	return DvmOptions{
+		Logger: log.New(ioutil.Discard, "", log.LstdFlags),
```
Comment (rgbkrk) [inline dvm-helper/internal/config/config.go]: Should we set other defaults for the `MirrorURL` and others here too? Or just rely on `""` being the default string and `false` being the default for `bool`?

Comment (carolynvs) [reply dvm-helper/internal/config/config.go]: I don't want to go changing too much at once, especially stuff that is unrelated to the original bug (doing a file move across disk partitions). 

I'm not terribly confident that I wouldn't cause regressions... 😊

Comment (rgbkrk) [reply dvm-helper/internal/config/config.go]: Makes sense.

**Comment by carolynvs** [comment]
@rgbkrk I've rebased to get it passing. Let me know if this is okay as is or if it needs another pass. 😀

File: dvm-helper/dockerversion/dockerversion.go [hunk 2]
```diff
@@ -102,26 +102,26 @@ func (version Version) buildDownloadURL(mirror string, forcePrerelease bool) (ur
 // version - the desired version.
 // mirrorURL - optional alternate download location.
 // binaryPath - full path to where the Docker client binary should be saved.
-func (version Version) Download(mirrorURL string, binaryPath string, l *log.Logger) error {
-	err := version.download(false, mirrorURL, binaryPath, l)
+func (version Version) Download(opts config.DvmOptions, binaryPath string) error {
+	err := version.download(false, opts, binaryPath)
```
Comment (rgbkrk) [inline dvm-helper/dockerversion/dockerversion.go]: Something @captainsafia pointed out to me is that we should [avoid the boolean trap](https://ariya.io/2011/08/hall-of-api-shame-boolean-trap). Since this was there before, I wouldn't bother changing it now. Might be good though, as I don't know if this means it's downloading or not.
